name: first-workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: |
            echo "Hii User"
            echo "welcome here to my first workflow"
      - name: Bye Bye Message
        run: echo "Bye Bye Everyone"
